version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    ECR_REPO_NAME: "brain-tasks-app"
    EKS_CLUSTER_NAME: "brain-tasks-cluster"
    CONTAINER_NAME: "brain-tasks"

phases:
  install:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "Image tag is $IMAGE_TAG"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $ECR_REPO_NAME:$IMAGE_TAG .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - echo Updating kubeconfig...
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
      - echo Updating deployment image...
      - sed -i "s|677929148535.dkr.ecr.us-east-1.amazonaws.com/brain-tasks-app:latest|$ECR_URI:$IMAGE_TAG|g" deployment.yaml
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl rollout status deployment/brain-tasks-deployment
      - echo Deployment complete!

artifacts:
  files:
    - deployment.yaml
    - service.yaml
    - buildspec.yml
